archivo/archidoc/src/main/java/deposito/model/DetalleUbicacion.java
/*
 * Created on 09-jun-2005
 *
 */
package deposito.model;

import transferencias.vos.IUnidadInstalacionVO;
import deposito.vos.HuecoVO;

/**
 * @author ABELRL
 * 
 */
public class DetalleUbicacion {
	HuecoVO hueco;
	IUnidadInstalacionVO unidadInstalacion;

	public HuecoVO getHueco() {
		return this.hueco;
	}

	public void setHueco(HuecoVO hueco) {
		this.hueco = hueco;
	}

	public IUnidadInstalacionVO getUnidadInstalacion() {
		return this.unidadInstalacion;
	}

	public void setUnidadInstalacion(IUnidadInstalacionVO unidadInstalacion) {
		this.unidadInstalacion = unidadInstalacion;
	}
}

archivo/archidoc/src/main/java/fondos/model/Fondo.java
package fondos.model;

import fondos.vos.FondoVO;

public class Fondo extends ElementoCuadroClasificacion implements FondoVO {

	public Fondo() {
	};

	String codPais;
	String codComunidad;
	String codArchivo;
	int tipofondo;
	String idEntProductora;

	boolean puedeSerEliminado = false;
	boolean puedeSerMovido = false;
	boolean permitidoModificarEntidadProductora = false;
	boolean permitidoModificarCodigo = false;
	boolean permitidoModificarArchivo = false;

	public String getCodArchivo() {
		return this.codArchivo;
	}

	public void setCodArchivo(String codArchivo) {
		this.codArchivo = codArchivo;
	}

	public String getCodComunidad() {
		return this.codComunidad;
	}

	public void setCodComunidad(String codComunidad) {
		this.codComunidad = codComunidad;
	}

	public String getCodPais() {
		return this.codPais;
	}

	public void setCodPais(String codPais) {
		this.codPais = codPais;
	}

	public String getDenominacion() {
		return this.titulo;
	}

	public void setDenominacion(String denominacion) {
		this.titulo = denominacion;
	}

	public String getIdEntProductora() {
		return this.idEntProductora;
	}

	public void setIdEntProductora(String idEntProductora) {
		this.idEntProductora = idEntProductora;
	}

	public int getTipofondo() {
		return tipofondo;
	}

	public String getCodigo() {
		return codigo;
	}

	public String getCodRefFondo() {
		return codRefFondo;
	}

	public void setCodRefFondo(String codRefFondo) {
		this.codRefFondo = codRefFondo;
	}

	public String getIdFondo() {
		return super.getId();
	}

	public String getTitulo() {
		return titulo;
	}

	public int getTipo() {
		return ElementoCuadroClasificacion.TIPO_FONDO;
	}

	public String getIdElementoCF() {
		return getId();
	}

	public void setIdElementoCF(String id) {
		setId(id);
	}

	// public Object clone(){
	// IFondo ret = new Fondo();
	// ret.setCodArchivo(codArchivo);
	// ret.setCodComunidad(codComunidad);
	// ret.setCodPais(codPais);
	// ret.setDenominacion(titulo);
	// // ret.setFinalCodigo(finalCodigo);
	// ret.setIdEntProductora(idEntProductora);
	// // ret.setInicioCodigo(inicioCodigo);
	// //codigo de referencia y codigo de fondo no hace falta(son dinamicos)
	//
	// return ret;
	// }

	public void setTipofondo(int tipoFondo) {
		this.tipofondo = tipoFondo;
	}

	public boolean isPublico() {
		return tipofondo == PUBLICO;
	}

	public boolean isEntidadProductoraModificable(
			boolean tieneUnidadesDocumentales) {
		return !tieneUnidadesDocumentales;
	}

	public String getCodReferencia() {
		return getCodRefFondo();
	}

	public boolean getPermitidoModificarCodigo() {
		return permitidoModificarCodigo;
	}

	public void setPermitidoModificarCodigo(boolean permitidoModificarCodigo) {
		this.permitidoModificarCodigo = permitidoModificarCodigo;
	}

	public boolean getPermitidoModificarEntidadProductora() {
		return permitidoModificarEntidadProductora;
	}

	public void setPermitidoModificarEntidadProductora(
			boolean permitidoModificarEntidadProductora) {
		this.permitidoModificarEntidadProductora = permitidoModificarEntidadProductora;
	}

	public boolean getPuedeSerEliminado() {
		return puedeSerEliminado;
	}

	public void setPuedeSerEliminado(boolean puedeSerEliminado) {
		this.puedeSerEliminado = puedeSerEliminado;
	}

	public boolean getPuedeSerMovido() {
		return puedeSerMovido;
	}

	public void setPuedeSerMovido(boolean puedeSerMovido) {
		this.puedeSerMovido = puedeSerMovido;
	}

	public boolean isPermitidoModificarArchivo() {
		return permitidoModificarArchivo;
	}

	public boolean getPermitidoModificarArchivo() {
		return permitidoModificarArchivo;
	}

	public void setPermitidoModificarArchivo(boolean permitidoModificarArchivo) {
		this.permitidoModificarArchivo = permitidoModificarArchivo;
	}
}

archivo/archidoc/src/main/java/deposito/actions/BusquedaUISEliminadasAction.java
package deposito.actions;

import gcontrol.vos.ArchivoVO;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import util.ErrorsTag;

import common.MotivoEliminacionUnidadInstalacion;
import common.actions.BaseAction;
import common.bi.GestionArchivosBI;
import common.navigation.KeysClientsInvocations;
import common.util.ArrayUtils;
import common.util.ListUtils;

import deposito.DepositoConstants;
import deposito.forms.BusquedaUISEliminadasForm;
import deposito.vos.BusquedaHistUInstDepositoVO;

public class BusquedaUISEliminadasAction extends BaseAction {

	public void nuevaBusquedaUIExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		saveCurrentInvocation(
				KeysClientsInvocations.DEPOSITO_BUSQUEDA_UIS_ELIMINADAS,
				request);

		removeInTemporalSession(request,
				DepositoConstants.LISTA_UIS_ELIMINADAS_KEY);
		removeInTemporalSession(request, DepositoConstants.LISTA_FORMATOS);
		setInTemporalSession(request, DepositoConstants.LISTA_FORMATOS,
				getGestorEstructuraDepositoBI(request).getFormatos());

		BusquedaUISEliminadasForm formulario = (BusquedaUISEliminadasForm) form;

		formulario
				.setMotivos(MotivoEliminacionUnidadInstalacion.MOTIVOS_ELIMINACION);

		// Obtener los posibles archivos receptores
		GestionArchivosBI serviceArchivos = getGestionArchivosBI(request);
		List ltArchivos = serviceArchivos.getArchivosXId(getAppUser(request)
				.getCustodyArchiveList().toArray());
		if (ListUtils.isNotEmpty(ltArchivos)) {
			if (ltArchivos.size() == 1) {
				ArchivoVO archivo = (ArchivoVO) ltArchivos.get(0);
				formulario.setIdArchivo(archivo.getId());
				formulario.setNombreArchivo(archivo.getNombre());

			} else {
				setInTemporalSession(request,
						DepositoConstants.LISTA_ARCHIVOS_USUARIO_KEY,
						ltArchivos);
			}
			setReturnActionFordward(request,
					mappings.findForward("form_busqueda"));
		} else {
			ActionErrors errors = new ActionErrors();
			errors.add(ErrorKeys.ERROR_USUARIO_SIN_ARCHIVOS, new ActionError(
					ErrorKeys.ERROR_USUARIO_SIN_ARCHIVOS));
			ErrorsTag.saveErrors(request, errors);
			goBackExecuteLogic(mappings, formulario, request, response);
		}
	}

	public void buscarUIExecuteLogic(ActionMapping mappings, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		BusquedaUISEliminadasForm formulario = (BusquedaUISEliminadasForm) form;

		List listaIdsArchivo = getAppUser(request).getCustodyArchiveList();
		BusquedaHistUInstDepositoVO busquedaHistUInstDepositoVO = formulario
				.getBusquedaHistUInstDepositoVO(listaIdsArchivo);

		if (ArrayUtils.isNotEmpty(busquedaHistUInstDepositoVO.getArchivos())) {
			List listaUis = getGestorEstructuraDepositoBI(request)
					.buscarHistoricoUnidadesInstalacionDeposito(
							busquedaHistUInstDepositoVO);
			setInTemporalSession(request,
					DepositoConstants.LISTA_UIS_ELIMINADAS_KEY, listaUis);
		} else {
			ActionErrors errors = new ActionErrors();
			errors.add(ErrorKeys.ERROR_USUARIO_SIN_ARCHIVOS, new ActionError(
					ErrorKeys.ERROR_USUARIO_SIN_ARCHIVOS));
			ErrorsTag.saveErrors(request, errors);
		}

		setReturnActionFordward(request, mappings.findForward("form_busqueda"));
	}
}

archivo/archidoc/src/main/java/deposito/actions/hueco/GestionEstadoHuecosAction.java
package deposito.actions.hueco;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import util.CollectionUtils;

import common.Constants;
import common.actions.BaseAction;
import common.bi.ServiceRepository;
import common.exceptions.ActionNotAllowedException;
import common.navigation.KeysClientsInvocations;
import common.util.StringUtils;

import deposito.DepositoConstants;
import deposito.actions.ErrorKeys;
import deposito.actions.asignable.ElementoAsignablePO;
import deposito.forms.GestionEstadoHuecoForm;
import deposito.forms.HuecoForm;
import deposito.model.GestorEstructuraDepositoBI;
import deposito.vos.ElementoAsignableVO;
import deposito.vos.HuecoID;
import deposito.vos.HuecoVO;

public class GestionEstadoHuecosAction extends BaseAction {

	private void prepareSeleccionHuecos(HttpServletRequest request,
			String idElementoAsignable) {

		ServiceRepository services = getServiceRepository(request);
		GestorEstructuraDepositoBI depositoBI = services
				.lookupGestorEstructuraDepositoBI();

		ElementoAsignableVO asignable = depositoBI
				.getElementoAsignable(idElementoAsignable);
		List listaHuecos = depositoBI.getHuecos(idElementoAsignable);
		CollectionUtils.transform(listaHuecos, HuecoToPO.getInstance(services));

		request.setAttribute(DepositoConstants.ELEMENTO_ASIGNABLE_KEY,
				new ElementoAsignablePO(asignable, services));
		request.setAttribute(DepositoConstants.LISTA_HUECOS_KEY, listaHuecos);
		request.setAttribute(
				DepositoConstants.EDITABLE_NUMERACION_KEY,
				new Boolean(depositoBI.isEditableNumeracion(asignable
						.getIddeposito())));
	}

	private boolean hayElementoASeleccionar(HttpServletRequest request,
			String estadoASeleccionar) {
		boolean hayElementoASeleccionar = false;
		List listaHuecos = (List) request
				.getAttribute(DepositoConstants.LISTA_HUECOS_KEY);
		for (int i = 0; !hayElementoASeleccionar && i < listaHuecos.size(); i++)
			hayElementoASeleccionar = estadoASeleccionar
					.equals(((HuecoVO) listaHuecos.get(i)).getEstado());
		return hayElementoASeleccionar;
	}

	public void habilitarHuecosExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		GestionEstadoHuecoForm estadoHuecoForm = (GestionEstadoHuecoForm) form;

		prepareSeleccionHuecos(request, estadoHuecoForm.getIdAsignable());

		boolean hayHuecosInutilizados = hayElementoASeleccionar(request,
				HuecoVO.INUTILIZADO_STATE);

		estadoHuecoForm.setEstadoAEstablecer(HuecoVO.LIBRE_STATE);
		estadoHuecoForm.setEstadoASeleccionar(HuecoVO.INUTILIZADO_STATE);
		estadoHuecoForm.setHayElementoASeleccionar(hayHuecosInutilizados);

		if (!hayHuecosInutilizados)
			obtenerErrores(request, true).add(ActionErrors.GLOBAL_ERROR,
					new ActionError(ErrorKeys.NO_HAY_HUECOS_A_SELECCIONAR));

		saveCurrentInvocation(KeysClientsInvocations.DEPOSITO_HABILITAR_HUECOS,
				request);
		setReturnActionFordward(request,
				mappings.findForward("seleccion_huecos"));
	}

	public void inhabilitarHuecosExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		GestionEstadoHuecoForm estadoHuecoForm = (GestionEstadoHuecoForm) form;

		prepareSeleccionHuecos(request, estadoHuecoForm.getIdAsignable());

		boolean hayHuecosLibres = hayElementoASeleccionar(request,
				HuecoVO.LIBRE_STATE);

		estadoHuecoForm.setEstadoAEstablecer(HuecoVO.INUTILIZADO_STATE);
		estadoHuecoForm.setEstadoASeleccionar(HuecoVO.LIBRE_STATE);
		estadoHuecoForm.setHayElementoASeleccionar(hayHuecosLibres);

		if (!hayHuecosLibres)
			obtenerErrores(request, true).add(ActionErrors.GLOBAL_ERROR,
					new ActionError(ErrorKeys.NO_HAY_HUECOS_A_SELECCIONAR));

		saveCurrentInvocation(
				KeysClientsInvocations.DEPOSITO_INHABILITAR_HUECOS, request);
		setReturnActionFordward(request,
				mappings.findForward("seleccion_huecos"));
	}

	public void setEstadoHuecosExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		GestionEstadoHuecoForm estadoHuecoForm = (GestionEstadoHuecoForm) form;
		ServiceRepository services = getServiceRepository(request);

		GestorEstructuraDepositoBI depositoBI = services
				.lookupGestorEstructuraDepositoBI();
		try {
			depositoBI.setEstadoHuecos(estadoHuecoForm.getIdAsignable(),
					estadoHuecoForm.getNumeroOrdenHueco(),
					estadoHuecoForm.getEstadoAEstablecer(),
					estadoHuecoForm.getEstadoASeleccionar());
			goBackExecuteLogic(mappings, form, request, response);
		} catch (ActionNotAllowedException e) {
			guardarError(request, e);
			goLastClientExecuteLogic(mappings, form, request, response);
		}
	}

	public void editarNumeracionExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		GestionEstadoHuecoForm estadoHuecoForm = (GestionEstadoHuecoForm) form;
		prepareSeleccionHuecos(request, estadoHuecoForm.getIdAsignable());
		removeInTemporalSession(request, DepositoConstants.HUECO_KEY);

		boolean hayHuecosLibres = hayElementoASeleccionar(request,
				HuecoVO.LIBRE_STATE);

		estadoHuecoForm.setHayElementoASeleccionar(hayHuecosLibres);
		if (!hayHuecosLibres)
			obtenerErrores(request, true).add(ActionErrors.GLOBAL_ERROR,
					new ActionError(ErrorKeys.NO_HAY_HUECOS_A_SELECCIONAR));

		saveCurrentInvocation(
				KeysClientsInvocations.DEPOSITO_EDITAR_NUMERACION_HUECOS,
				request);
		setReturnActionFordward(request,
				mappings.findForward("seleccion_uis_editar"));
	}

	public void setNumeracionExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		GestionEstadoHuecoForm estadoHuecoForm = (GestionEstadoHuecoForm) form;
		ServiceRepository services = getServiceRepository(request);
		GestorEstructuraDepositoBI depositoBI = services
				.lookupGestorEstructuraDepositoBI();

		HuecoID huecoID = new HuecoID(estadoHuecoForm.getIdAsignable(),
				estadoHuecoForm.getNumeroOrdenHueco()[0]);
		HuecoVO huecoVO = depositoBI.getInfoHueco(huecoID);
		HuecoPO huecoSelected = new HuecoPO(huecoVO, services);
		estadoHuecoForm.setIdHueco(huecoID.getIdpadre() + ":"
				+ huecoID.getNumorden());

		String numeracion = Constants.STRING_EMPTY;

		if (huecoVO != null && StringUtils.isNotBlank(huecoVO.getNumeracion())) {
			numeracion = huecoVO.getNumeracion().trim();
		}

		estadoHuecoForm.setNumeracion(numeracion);
		setInTemporalSession(request, DepositoConstants.HUECO_KEY,
				huecoSelected);
		request.setAttribute(DepositoConstants.MOSTRAR_RENUMERACION_KEY,
				new Boolean(StringUtils.isNumeric(numeracion)));

		saveCurrentInvocation(
				KeysClientsInvocations.DEPOSITO_EDITAR_NUMERACION_HUECOS,
				request);

		setReturnActionFordward(request,
				mappings.findForward("editar_numeracion"));
	}

	public void saveNumeracionExecuteLogic(ActionMapping mappings,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		GestionEstadoHuecoForm estadoHuecoForm = (GestionEstadoHuecoForm) form;
		ServiceRepository services = getServiceRepository(request);
		GestorEstructuraDepositoBI depositoBI = services
				.lookupGestorEstructuraDepositoBI();
		String idHueco = estadoHuecoForm.getIdHueco();
		HuecoID huecoID = HuecoForm.getHuecoID(idHueco);
		String nuevaNumeracion = estadoHuecoForm.getNumeracion();
		if (StringUtils.isNotEmpty(nuevaNumeracion)) {
			// Si se pone renumerar se comprueba si se puede hacer y se lleva a
			// cabo
			// sino se actualiza la numeracion del hueco en la base de datos
			boolean renumerar = estadoHuecoForm.isRenumerar();
			try {
				depositoBI.renumerarHuecos(huecoID, nuevaNumeracion.trim(),
						renumerar);
				goBackExecuteLogic(mappings, estadoHuecoForm, request, response);
			} catch (ActionNotAllowedException e) {
				guardarError(request, e);
				setReturnActionFordward(request,
						mappings.findForward("editar_numeracion"));
			}
		} else {
			obtenerErrores(request, true).add(
					ActionErrors.GLOBAL_ERROR,
					new ActionError(
							DepositoConstants.ERROR_EDITAR_NUMERACION_VACIA));
			setReturnActionFordward(request,
					mappings.findForward("editar_numeracion"));
		}
	}
}

archivo/archidoc/src/main/webapp/pages/tiles/deposito/niveles/cuerpo_agregarNivelDescendiente.jsp
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-html-el.tld" prefix="html-el" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="http://java.sun.com/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="/WEB-INF/displaytag.tld" prefix="display" %>
<%@ taglib uri="/WEB-INF/taglibs/displaydepositotags.tld" prefix="archivo"%>

<bean:struts id="actionMapping" mapping="/gestionNivelesCuadro" />
<c:set var="formName" value="${actionMapping.name}" />
<c:set var="form" value="${requestScope[formName]}" />
<c:set var="listaPosiblesHijos" value="${requestScope[appConstants.fondos.LISTA_POSIBLES_NIVELES_HIJO]}" />
<c:set var="nivel" value="${requestScope[appConstants.fondos.NIVEL_CF_KEY]}"/>

<html:form action="/gestionNivelesCuadro" styleId="formulario">
	<input type="hidden" name="method" value="addNivelDescendiente">
	<input type="hidden" name="idNivel" value="<c:out value="${nivel.id}" />">
	<input type="hidden" name="tipoNivel" value="<c:out value="${nivel.tipo}" />">
	
	<tiles:insert template="/pages/tiles/PABoxLayout.jsp">

		<tiles:put name="boxTitle" direct="true">
			<bean:message key="NavigationTitle_CUADRO_CLASIFICACION_NIVELES_AGREGAR_NIVEL"/>
		</tiles:put>
		<tiles:put name="buttonBar" direct="true">
		
			<table cellpadding=0 cellspacing=0>
			<tr>
				<logic:notEmpty name="listaPosiblesHijos">
				<td>
					<a class="etiquetaAzul12Bold" href="javascript:document.forms['<c:out value="${actionMapping.name}" />'].submit()" >
					<html:img page="/pages/images/Ok_Si.gif" altKey="archigest.archivo.aceptar" titleKey="archigest.archivo.aceptar" styleClass="imgTextMiddle" />
					&nbsp;<bean:message key="archigest.archivo.aceptar"/></a>
	            </td>
	            </logic:notEmpty>
				<td width="20">&nbsp;</td>
				<td>
					<tiles:insert definition="button.closeButton" flush="true"/>
				</td>
			</tr>
			</table>
		</tiles:put>
		
		<c:url var="paginationURL" value="/action/gestionNivelesCuadro" >
			<c:param name="method" value="agregarNivelHijo"/>
			<c:param name="idNivel" value="${nivel.id}"/>
		</c:url>
		<jsp:useBean id="paginationURL" type="java.lang.String" />
		<tiles:put name="boxContent" direct="true">
			<div class="bloque">	
				<div class="separador10">&nbsp;</div>
				<display:table name="pageScope.listaPosiblesHijos" 
						id="nivel" 
						htmlId="listaPosiblesHijos"
						sort="list" 
						style="width:98%;margin-left:auto;margin-right:auto"
						requestURI='<%=paginationURL%>'
						excludedParams="*"
						pagesize="15">
						
					<display:setProperty name="basic.msg.empty_list">
						<bean:message key="archigest.archivo.fondos.cf.niveles.listaPosiblesHijosVacia"/>
					</display:setProperty>
					
					<display:column style="width:10px" title="">
						<input type="checkbox" name="descendientes" value="<c:out value="${nivel.id}" />" >
					</display:column>												
																		
					<display:column titleKey="archigest.archivo.nombre" sortProperty="nombre" sortable="true" headerClass="sortable">						
						<bean:write name="nivel" property="nombre"/>																																
					</display:column>
				</display:table>
				<div class="separador10">&nbsp;</div>
			</div>
		</tiles:put>
	</tiles:insert>
</html:form>

archivo/archidoc/src/main/webapp/pages/tiles/deposito/niveles/cuerpo_listadoNiveles.jsp
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-html-el.tld" prefix="html-el" %>
<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %>
<%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %>
<%@ taglib uri="http://java.sun.com/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="/WEB-INF/displaytag.tld" prefix="display" %>
<%@ taglib uri="/WEB-INF/taglibs/displaydepositotags.tld" prefix="archivo"%>

<bean:struts id="actionMapping" mapping="/gestionNivelesDeposito" />
<c:set var="formName" value="${actionMapping.name}" />
<c:set var="form" value="${requestScope[formName]}" />
<c:set var="listaNiveles" value="${sessionScope[appConstants.deposito.LISTA_NIVELES_KEY]}" />

	<tiles:insert template="/pages/tiles/PABoxLayout.jsp">

		<tiles:put name="boxTitle" direct="true">
			<bean:message key="NavigationTitle_DEPOSITO_NIVELES"/>
		</tiles:put>
		<tiles:put name="buttonBar" direct="true">

			<table cellpadding=0 cellspacing=0>
			<tr>
				<td>
					<tiles:insert definition="button.closeButton" flush="true"/>
				</td>
			</tr>
			</table>
		</tiles:put>

		<c:url var="paginationURL" value="/action/gestionNivelesDeposito" >
			<c:param name="method" value="init"/>
		</c:url>
		<jsp:useBean id="paginationURL" type="java.lang.String" />
		<tiles:put name="boxContent" direct="true">
			<div class="bloque">
				<div class="separador10">&nbsp;</div>
				<display:table name="pageScope.listaNiveles"
						id="nivel"
						htmlId="listaNiveles"
						sort="list"
						style="width:98%;margin-left:auto;margin-right:auto"
						requestURI='<%=paginationURL%>'
						excludedParams="*"
						pagesize="15">

					<display:setProperty name="basic.msg.empty_list">
						<bean:message key="archigest.archivo.depositos.niveles.listaVacia"/>
					</display:setProperty>
					<display:column style="width:30px;text-align:center">
						<html-el:img page="/pages/images/arboles/${nivel.imagen}" styleClass="imgTextMiddle"
								altKey="${nivel.nombre}" titleKey="${nivel.nombre}"/>
					</display:column>

					<display:column style="width:60px;text-align:center" titleKey="archigest.archivo.depositos.niveles.asignable">
						<c:choose>
			          		<c:when test="${nivel.tipoAsignable}">
								<bean:message key="archigest.archivo.si"/>
			          		</c:when>
			          		<c:otherwise>
			          			<bean:message key="archigest.archivo.no"/>
			          		</c:otherwise>
			          	</c:choose>

					</display:column>
					<display:column titleKey="archigest.archivo.depositos.niveles.nombre" sortProperty="nombre" sortable="true" headerClass="sortable">
						<c:url var="datosNivelURL" value="/action/gestionNivelesDeposito">
							<c:param name="method" value="verNivel"/>
							<c:param name="idNivel" value="${nivel.id}" />
						</c:url>

						<a href='<c:out value="${datosNivelURL}" escapeXml="false" />' class="tdlink">
							<c:out value="${nivel.nombre}"/>
						</a>
					</display:column>
				</display:table>
				<div class="separador10">&nbsp;</div>
			</div>
		</tiles:put>
	</tiles:insert>